- name: create-rds-instance
  hosts: localhost
  gather_facts : false

  tasks:
    - name: provision postgres rds instance
      rds:
        command: create
        size: 20
        availability_zone:  azs1
        instance_type: instance_type1 
        db_name:  db_name1
        db_subnet_groups: db_subnet_groups1
        engine: engine1
        engine_version: engine_version1
        master_user_password: master_user_password1
        master_username:  master_username1
        region: region1
        storage_type: storage_type1
        tags:
          environment: test
