- name: create-rds-instance
  hosts: localhost
  connection: local
  gather_facts : false

  tasks:
    - name: provision postgres rds instance
      rds:
        command: create
        allocated_storage: 20
        availability_zone: "us-west-2b"
        db_instance_class: "db.m6g.large"
        db_name: "PostgreSQL"
        db_subnet_group_name: "dbsubnetgroup"
        engine: "postgres"
        engine_version: "13.3"
        master_user_password: "secret"
        master_username: "dbmaster"
        region: "us-west-1"
        storage_type: "standard"
        tags:
          environment: test
