- name: create-rds-instance
  hosts: localhost
  connection: local
  gather_facts : false

  tasks:
    - name: provision postgres rds instance
      rds:
        command: create
        allocated_storage: "AllocatedStorage1"
        availability_zone: "azs"
        db_instance_class: "DBInstanceClass1"
        db_name: "DBName"
        db_subnet_group_name: "SubnetGroupName1"
        engine: "Engine1"
        engine_version: "EngineVersion1"
        master_user_password: "MasterUserPassword"
        master_username: "MasterUsername"
        region: "Region1"
        storage_type: "StorageType"
        tags:
          environment: test
