AWSTemplateFormatVersion: "2010-09-09"
Description: An example template for a creating Rds.
Resources: 
 Rds: 
  Type: AWS::RDS::DBInstance
  Properties: 
    AllocatedStorage: 20
    Engine: engine_type
    EngineVersion: engine_version1
    DBInstanceClass: instance_class1
    DBName: dbname
    MasterUsername: user_name
    MasterUserPassword: passwd
    AvailabilityZone: azs
    MultiAZ: multiavailability_zone
    ReplicaMode: Readreplica1
    StorageEncrypted: storage1
    StorageType: STselect
    DeletionProtection: deleteprotection1
    VPCSecurityGroups: 
     - dbsecurity
    DBSubnetGroupName: SubnetA



    
