NewVolume:
  Type: AWS::EC2::Volume
  Properties: 
     Volume_type: "Volume_type1"
     volume_size: "volume_size1"
    Encrypted: "Encrypted1"
    AvailabilityZone: "AvailabilityZone1"
    Tags:
      - Name: "EBS-Name"
 
  
